version: '3'
services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.0
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.0/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            # - '${HMR_PORT:-8080}:8080' HotModuleReload?
            - '3000:3000'
            - '3001:3001'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_SESSION: 1
            XDEBUG_MODE: 'debug'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
            - './.debug:/tmp'
        networks:
            - sail
        depends_on:
            - mysql
            - redis
    mysql:
      image: 'mysql:8.0'
      cap_add:
        - SYS_NICE  # CAP_SYS_NICE
      ports:
        - '${FORWARD_DB_PORT:-3306}:3306'
      environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      volumes:
        - 'sailmysql:/var/lib/mysql'
      networks:
        - sail
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sailredis:/data'
        networks:
            - sail
    mailhog:
      image: 'mailhog/mailhog:latest'
      ports:
        - '${FORWARD_MAILHOG_PORT:-1025}:1025'
        - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
      networks:
        - sail
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      depends_on:
        - mysql
      ports:
        - 8181:80
      environment:
        PMA_HOST: mysql
        MYSQL_USERNAME: '${DB_USERNAME}'
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        UPLOAD_LIMIT: '1024M'
        MEMORY_LIMIT: '1024M'
        MAX_EXECUTION_TIME: 300
      networks:
        - sail
networks:
  sail:
        driver: bridge
volumes:
    sailmysql:
        driver: local
    sailredis:
        driver: local
