#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

if [[ "${TRACE-0}" == "1" ]]; then
    set -o xtrace
fi

if [[ "${1-}" =~ ^-*h(elp)?$ ]]; then
    echo 'Usage: ./script.sh one two'
    exit
fi

# now you can link this file and all the commands you run
# will think that are in separate folders
cd "$(dirname "$0")"

AUTOCOMPLETE_WORDS="${AUTOCOMPLETE_WORDS:-} mypath"
PATH=


function shortlist { # of functions inside this script, for autocomplete
   echo $AUTOCOMPLETE_WORDS
}

function mypath {
   pwd
}

"$@"

unset PATH
