#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
if [[ "${TRACE-0}" == "1" ]]; then
    set -o xtrace
fi

if [[ "${1-}" =~ ^-*h(elp)?$ ]]; then
    echo 'Usage: ./script.sh one two'
    exit
fi

cd "$(dirname "$0")"

PATH=

function shortlist { # of functions inside this script, for autocomplete
   echo help 
}

function mypath {
   pwd
}

"$@"

unset PATH
